-- Salvar novo token do Melhor Envio
-- Execute este SQL no Supabase SQL Editor

-- Deletar configuração antiga (se existir)
DELETE FROM config_melhorenvio WHERE id = 1;

-- Inserir novo token
INSERT INTO config_melhorenvio (
  id,
  access_token,
  refresh_token,
  token_type,
  created_at,
  updated_at
) VALUES (
  1,
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjUwYmJmN2Q5NGJiOTJmYzYyZWM3NGJhMjIyYWQ4NTQxZmJhYmRhZDI1OTIzZThkY2U4ZWFjNWMzOWVlMzRhZjVhMjMzZDMzOWFiOWY2MjgiLCJpYXQiOjE3NjIwOTMzMTEuOTQwNDY0LCJuYmYiOjE3NjIwOTMzMTEuOTQwNDY2LCJleHAiOjE3OTM2MjkzMTEuOTI2MDUxLCJzdWIiOiIzNjBiM2Y1OC01NjQ2LTRiNzYtYjIwNi0zZDllNzE3YjcwOWYiLCJzY29wZXMiOlsiY2FydC1yZWFkIiwiY2FydC13cml0ZSIsImNvbXBhbmllcy1yZWFkIiwiY29tcGFuaWVzLXdyaXRlIiwiY291cG9ucy1yZWFkIiwiY291cG9ucy13cml0ZSIsIm5vdGlmaWNhdGlvbnMtcmVhZCIsIm9yZGVycy1yZWFkIiwicHJvZHVjdHMtcmVhZCIsInByb2R1Y3RzLWRlc3Ryb3kiLCJwcm9kdWN0cy13cml0ZSIsInB1cmNoYXNlcy1yZWFkIiwic2hpcHBpbmctY2FsY3VsYXRlIiwic2hpcHBpbmctY2FuY2VsIiwic2hpcHBpbmctY2hlY2tvdXQiLCJzaGlwcGluZy1jb21wYW5pZXMiLCJzaGlwcGluZy1nZW5lcmF0ZSIsInNoaXBwaW5nLXByZXZpZXciLCJzaGlwcGluZy1wcmludCIsInNoaXBwaW5nLXNoYXJlIiwic2hpcHBpbmctdHJhY2tpbmciLCJlY29tbWVyY2Utc2hpcHBpbmciLCJ0cmFuc2FjdGlvbnMtcmVhZCIsInVzZXJzLXJlYWQiLCJ1c2Vycy13cml0ZSIsIndlYmhvb2tzLXJlYWQiLCJ3ZWJob29rcy13cml0ZSIsIndlYmhvb2tzLWRlbGV0ZSIsInRkZWFsZXItd2ViaG9vayJdfQ.BzqAhv3Qq5XULUxV6sM0Iv8cabGI_s0XbNAypHekXnR1qQLxeEMHBA1vJLAbtwyzFxVk-zE0F4cBgYxMWhkOV8r0FihfIh1CTh42lhnUi1tQWLQrR3eo2IJ1TF6JdyKW41uNvj1uHrRFK_WYMKF6a7K3f1tWSpUYI8joD_MxQBda_VwcNjn6ZafebYx7Y_6w1CRHyUPtkRtzPDd6Nsc_NXx0aZbroJnY4jvrPKDAM9aty7X6sJQtSze5iaTJTrvYLjIj0DBHQ4aEG6ldF4yCTEIjCQosANFhJn48rIdgMytj00_ZRayVPx9y1tsxIHtbOtJbwiYqH2NlHjswFQGD_ATbrIqVhL7yM114-h0UIoyEwX9J6jmCsM8Ulz8MalMLeszsImTraC1QLQIgAFSRBvVeHoM-wJVx-semWb-AZ-L4A9jQq7ttkAYmi1NJVjk7ES2wkHVPjyyL-NDxJZx5gofhYqFDG7lqSfxdhJnwAI6vGbRbjssMVh6rL4Awjw38ax0dyn9KT7dLQYKM-w_-vowIwZco_Fo_LPecbVDyAPwaiMLseB6Rmmy9CvnVn3PJ519VXq4A63XBLwDG2_vUGZ5MPi6ZOMPSpLTViFxZ67Onwz25j3FVN5aaXiYyhlnaPzHnIM2gCYp4sOo6BtaInALIJig9_Aurkq5OOLEaCB0',
  'not-applicable',
  'Bearer',
  NOW(),
  NOW()
);

-- Verificar se foi salvo
SELECT id, LEFT(access_token, 50) as token_preview, token_type, created_at, updated_at 
FROM config_melhorenvio 
WHERE id = 1;
